mazintech/college/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from dal import autocomplete

import views
from college.graphs import *
# from mazintech.autocomplete import *

from .models import *
from mazintech.models import *

urlpatterns = [
    url(r'^student/edit/(?P<student_id>\d+)/$', views.edit_student, name='edit_student'),
    url(r'^student/add/$', views.edit_student, name='add_student'), 
    url(r'^students/$', views.students, name='students'),
    url(r'^enrolments/$', views.enrolments, name='enrolments'),
    url(r'^courses/$', views.courses, name='courses'),
    url(r'^student-enrolment/edit/(?P<enrolment_id>\d+)/$', views.edit_enrolment, name='edit_enrolment'),
    url(r'^student-enrolment/add/(?P<student_id>\d+)/$', views.edit_enrolment, name='add_enrolment'),
    url(r'^student-enrolment/$', views.edit_enrolment, name='add_new_enrolment'),
    url(r'^course/edit/(?P<course_id>\d+)/$', views.edit_course, name='edit_course'),
    url(r'^course/add/$', views.edit_course, name='add_course'),
    url(r'^course-delete/$', views.delete_course, name='delete_course'),
    url(r'^student-delete/$', views.delete_student, name='delete_student'),
    url(r'^enrolment-delete/$', views.delete_enrolment, name='delete_enrolment'),
    url(r'^course-totals/$', courseTotalEnrolmentData.as_view(), name='course_totals'),
    url(r'^current-totals/$', currentTotalEnrolmentData.as_view(), name='current_totals'),
    url(r'^regional-totals/$', regionalTotalEnrolmentData.as_view(), name='regional_totals'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mazintech/mazintech/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from django_js_reverse.views import urls_js
from models import RegionAutoComplete,DistrictAutoComplete

urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^region_autocomplete/$', RegionAutoComplete.as_view(), name='region_autocomplete'),
    url(r'^district_autocomplete/$', DistrictAutoComplete.as_view(), name='district_autocomplete'),

    url(r'^jsreverse/$', urls_js, name='js_reverse'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout,{'next_page':'/'}, name='logout'),

    url(r'^about/$', views.about, name='about'),
    url(r'^users$', views.users, name='users'),
    url(r'^users/college-admins/(?P<college_administrators>\d+)/$', views.users, name='college_admins'),
    url(r'^user/add/$', views.user_edit, name='user_add'),
    url(r'^user/edit/(?P<user_id>\d+)/$', views.user_edit, name='user_edit'),

    url(r'^', include('college.urls', namespace='college')),

    url(r'^regions$', views.view_regions, name='view_regions'),
    url(r'^branches$', views.view_branches, name='view_branches'),

    url(r'^downloads/$', views.downloads_list, name="view_downloads"),
    url(r'^downloads/(?P<file_id>\d+)/$', views.file_download_task, name="file_download"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mazintech/college/models.py
from django.db import models
from lib.models import BaseModel
from lib.fields import ProtectedForeignKey
from django.core.validators import MaxValueValidator, MinValueValidator
from simple_history.models import HistoricalRecords
from datetime import datetime
from datetime import timedelta
from django.db.models import Sum
from django.conf import settings

from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import View
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.contrib.auth.models import User

class Course(BaseModel):
    course_name = models.CharField(max_length=255, unique=True, null=False, blank=False)

    def __unicode__(self):
        return self.course_name

    def delete(self, logged_in_user):
        self.deleted = True
        self.modified_by = logged_in_user
        self.changed_at = datetime.now()
        self.save()

    @property
    def current_enrolment(self):
        current_year = datetime.now().year
        enrolment = self.course_enrolment.filter(enrolment_year=current_year).count()
        return enrolment

    @property
    def total_enrolment(self):
        enrolment = self.course_enrolment.all().count()
        return enrolment

class Student(BaseModel):
    first_name = models.CharField(max_length=255, null=True, blank=True, verbose_name='First Name')
    surname = models.CharField(max_length=255, null=True, blank=True, verbose_name='Surname')
    date_of_birth = models.DateTimeField(null=True, blank=True, verbose_name='Date Of Birth')
    id_number = models.CharField(default=None, max_length=50, null=True, blank=True, verbose_name='ID Number')
    passport_number = models.CharField(default=None, max_length=50, null=True, blank=True, verbose_name='Passport Number')
    gender = models.CharField(max_length=50, null=False, blank=False, verbose_name='Gender',
                                choices=(('male','Male'),('female','Female')))
    region = ProtectedForeignKey('mazintech.Region', null = True, blank = True, related_name='student_region')
    district = ProtectedForeignKey('mazintech.Branch', null = True, blank = True, related_name='student_district')
    address = ProtectedForeignKey('mazintech.Address', null = True, blank = True, related_name='student_address')
    contact = ProtectedForeignKey('mazintech.Contact', null = True, blank = True, related_name='student_contact')
    created_by = ProtectedForeignKey('mazintech.MazintechUser', null=False, blank=False, related_name='created_student')
    modified_by = ProtectedForeignKey('mazintech.MazintechUser', null=True, blank=True, related_name='modified_student')
    history = HistoricalRecords()

    def __unicode__(self):
        return '{} {}'.format(self.first_name,self.surname)

    def delete(self, logged_in_user):
        self.deleted = True
        self.modified_by = logged_in_user
        self.changed_at = datetime.now()
        self.save()

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name,self.surname)
    
    @property
    def course(self):
        course = self.student_enrolment.order_by('-enrolment_year').first()
        return course.course.course_name if course else ''
    
    @property
    def course_year(self):
        course = self.student_enrolment.order_by('-enrolment_year').first()
        return course.enrolment_year if course else ''

class Enrolment(BaseModel):
    student = ProtectedForeignKey('college.Student', null = True, blank = True, related_name='student_enrolment')
    course = ProtectedForeignKey('college.Course', null = True, blank = True, related_name='course_enrolment')
    application_signed = models.DateTimeField(null=True, blank=True, verbose_name='Date Signed')
    enrolment_year = models.IntegerField(null=False, blank=False, default=0, verbose_name='enrolment_year',
                                  validators=[MinValueValidator(0)])
    application_fee = models.IntegerField(null=False, blank=False, default=0, verbose_name='Application Fee',
                                  validators=[MinValueValidator(0)])
    created_by = ProtectedForeignKey('mazintech.MazintechUser', null=False, blank=False, related_name='created_enrolment')
    modified_by = ProtectedForeignKey('mazintech.MazintechUser', null=True, blank=True, related_name='modified_enrolment')
    history = HistoricalRecords()

    def delete(self, logged_in_user):
        self.deleted = True
        self.modified_by = logged_in_user
        self.changed_at = datetime.now()
        self.save()

class StudentDocumentUploads(BaseModel):
    description = models.CharField(max_length=255, null=False, blank=False,)

    def __unicode__(self):
                return self.description

class StudentDocument(BaseModel):

    student = ProtectedForeignKey('college.Student', null=False, blank=False, related_name='student_documents')
    document = ProtectedForeignKey('mazintech.Document', null=False, blank=False)
    document_type = models.ManyToManyField(StudentDocumentUploads, verbose_name='Document Type')
    created_by = ProtectedForeignKey('mazintech.MazintechUser', null=False, blank=False, related_name='created_student_documents')
    modified_by = ProtectedForeignKey('mazintech.MazintechUser', null=True, blank=True, related_name='modified_student_documents')


# class courseTotalEnrolmentData(APIView):
#     authentication_classes = []
#     permission_classes = []

#     def get(self, request, format=None):
#         courses = Course.objects.exclude(deleted=True).order_by('course_name')
#         totals = []
#         labels = []
#         for course in courses:
#             total = course.total_enrolment
#             label = course.course_name
#             totals.append(total)
#             labels.append(label)

#         data = {
#             'labels':labels, 
#             'values':totals,
#             }

#         return Response(data)

#         

mazintech/college/forms.py
import os

from django.conf import settings
from django import forms
from django.db.models import Q
from datetime import datetime, timedelta
from django.db.models.functions import Concat
from django.db.models import Value as V
from django.forms.widgets import *
from models import *
from rest_framework import fields, serializers
from django.core.urlresolvers import reverse
from mazintech.models import *
from dal import autocomplete, forward
from django.forms.widgets import RadioSelect

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_name']


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        exclude = ['deleted', 'created_by', 'modified_by']

    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        
        for f in self.fields:
            self.fields[f].widget.attrs['required'] = 'true'
        self.fields['date_of_birth'].widget.attrs['class'] = 'date_field'


class EnrolmentForm(forms.ModelForm):
    class Meta:
        model = Enrolment
        exclude = ['deleted', 'created_by', 'modified_by']

    def __init__(self, *args, **kwargs):
        super(EnrolmentForm, self).__init__(*args, **kwargs)
        
        for f in self.fields:
            self.fields[f].widget.attrs['required'] = 'true'
        self.fields['application_signed'].widget.attrs['class'] = 'date_field'


class StudentFilterForm(forms.Form):
    student_name = forms.CharField(required = False, label="Student Name")
    student_surname = forms.CharField(required = False, label="Student Surname")
    date_from = forms.DateTimeField(required=False,label='From Date')
    date_to   = forms.DateTimeField(required=False,label='To Date')
    id_number = forms.CharField(required = False, label="ID Number")
    course = forms.CharField(required = False, label="Course")
    enrolment_year = forms.CharField(required = False, label="Enrolment Year")

    def __init__(self, *args, **kwargs):
        super(StudentFilterForm, self).__init__(*args, **kwargs)

    def filter(self, students):
        if self.cleaned_data is not None:
            if self.cleaned_data['student_name']:
                students = students.filter(first_name__icontains=self.cleaned_data['student_name'])

            if self.cleaned_data['student_surname']:
                students = students.filter(surname__icontains=self.cleaned_data['student_surname'])

            if self.cleaned_data['enrolment_year']:
                students = students.filter(student_enrolment__enrolment_year=self.cleaned_data['enrolment_year'])

            if self.cleaned_data['id_number']:
                students = students.filter(Q(id_number=self.cleaned_data['id_number'])| 
                                           Q(pasport_number=self.cleaned_data['id_number']))
            if self.cleaned_data['course']:
                courses = Course.objects.filter(course_name__icontains=self.cleaned_data['course'])
                students = students.filter(student_enrolment__course__course_name__icontains=self.cleaned_data['course'])

            if self.cleaned_data['date_to']:
                students = students.filter(created_at__lte=self.cleaned_data['date_to'])

            if self.cleaned_data['date_from']:
                students = students.filter(created_at__gte=self.cleaned_data['date_from'])

        return students

class StudentDocumentForm(forms.ModelForm):

    class Meta:
        model = StudentDocument
        fields = ['document_type']

    def __init__(self, *args, **kwargs):
        super(StudentDocumentForm, self).__init__(*args, **kwargs)
        self.fields['document_type'].widget = SelectMultiple()
        self.fields['document_type'].widget.attrs['class'] = 'multi_select'
        self.fields['document_type'].queryset = StudentDocumentUploads.objects.all()


class StudentFileForm(forms.ModelForm):

    class Meta:
        model = Document
        fields = ['document']

class EnrolmentFilterForm(forms.Form):
    course = forms.CharField(required = False, label="Course")
    date_type = forms.ChoiceField(required = False, label = 'Date Type',
                                  choices = (('captured','Date Captured'),
                                             ('signed','Date Signed')))
    student_name = forms.CharField(required = False, label="Student Name")
    student_surname = forms.CharField(required = False, label="Student Surname")
    date_from = forms.DateTimeField(required=False,label='From Date')
    date_to   = forms.DateTimeField(required=False,label='To Date')    
    enrolment_year = forms.CharField(required = False, label="Enrolment Year")

    def __init__(self, *args, **kwargs):
        super(EnrolmentFilterForm, self).__init__(*args, **kwargs)

    def filter(self, students):
        if self.cleaned_data is not None:
            if self.cleaned_data['student_name']:
                students = students.filter(student__first_name__icontains=self.cleaned_data['student_name'])

            if self.cleaned_data['student_surname']:
                students = students.filter(student__surname__icontains=self.cleaned_data['student_surname'])

            if self.cleaned_data['enrolment_year']:
                students = students.filter(enrolment_year=self.cleaned_data['enrolment_year'])

            if self.cleaned_data['course']:
                students = students.filter(course__course_name__icontains=self.cleaned_data['course'])
            
            if self.cleaned_data['date_type'] == "captured":
                if self.cleaned_data['date_to']:
                    students = students.filter(created_at__lte=self.cleaned_data['date_to'])

                if self.cleaned_data['date_from']:
                    students = students.filter(created_at__gte=self.cleaned_data['date_from'])
            else:
                if self.cleaned_data['date_to']:
                    students = students.filter(application_signed__lte=self.cleaned_data['date_to'])

                if self.cleaned_data['date_from']:
                    students = students.filter(application_signed__gte=self.cleaned_data['date_from'])

        return students

class CourseFilterForm(forms.Form):
    course = forms.CharField(required = False, label="Course") 

    def __init__(self, *args, **kwargs):
        super(CourseFilterForm, self).__init__(*args, **kwargs)

    def filter(self, courses):
        if self.cleaned_data is not None:
            if self.cleaned_data['course']:
                courses = courses.filter(course_name__icontains=self.cleaned_data['course'])
        return courses

mazintech/templates/college/_courses_list.html
{% load el_pagination_tags %}
<script type="text/javascript">
  delete_course = function(id, row_id){
    $("<div><h4>Are you sure you want to delete this course record?</h4></div>").dialog({
        buttons: {
          Yes: function(){

            $.ajax({
            context: row_id,
            type: 'post',
            url: "{% url 'college:delete_course' %}",
            data: {id: id},
            dataType: 'json',
            success:  function(response){
                        if(response.success)
                        {
                          $("<div />").dialog({
                            title: 'Delete Course',
                            open: function(){
                              markup = '<h4>Course record deleted successfully</h4>';
                              $(this).html(markup);
                            },
                            buttons: {
                            Ok: function () {
                                  $(this).dialog("close");
                                }
                            }
                          });
                          $(row_id).remove();
                        }
                        else
                        {
                          $("<div />").dialog({
                            title: 'Delete Failure',
                            open: function(){
                              markup = '<h4>A problem occurred while deleting the course record</h4>';
                              $(this).html(markup);
                            },
                            buttons: {
                            Ok: function () {
                                  $(this).dialog("close");
                                }
                            }
                          });
                        }
                      }
            });
              $(this).dialog("close");
          },
          Cancel: function(){

            $(this).dialog("close");

          }
        }
    });
  }
  </script>
<table id="" class="table table-hover ">
  <tr>
    <th>Course Name</th>
    <th>Current Enrolment</th>
    <th>Total Enrolment</th>
    <th>Edit</th>
    <th>Del</th>
  </tr>

  {% paginate all_courses %}
  {% for course in all_courses %}

  <tr id=row_{{course.id}}>    
    <td>{{ course.course_name|default_if_none:"" }}</td> 
    <td>{{ course.current_enrolment|default_if_none:"" }}</td>
    <td>{{ course.total_enrolment|default_if_none:"" }}</td>
    <td>
     <a href="{% url 'college:edit_course' course.id %}" data-toggle="" data-toggle="tooltip" data-placement="right" title="Edit Course">
        <i class="far fa-edit"></i></i></a>
    </td>
    <td>
      <a  href="" onclick="delete_course({{course.id}}, row_{{course.id}});return false;"data-toggle="" data-toggle="tooltip" data-placement="right" title="Delete Course"><i class="far fa-trash-alt"></i></a>
      </td>
  </tr>
  {% endfor %}
  <tr>
    <td colspan='13' style="text-align: center">
    <div class="center">
      <div class="pagination">
        {% show_pages %}
      </div>
    </div>
    </td>
  </tr>
</table>

mazintech/templates/college/_enrolments_list.html
{% load el_pagination_tags %}
<script type="text/javascript">
  delete_policy_comment = function(id, row_id){
    $("<div><h4>Are you sure you want to delete this student enrolment record?</h4></div>").dialog({
        buttons: {
          Yes: function(){

            $.ajax({
            context: row_id,
            type: 'post',
            url: "{% url 'college:delete_enrolment' %}",
            data: {id: id},
            dataType: 'json',
            success:  function(response){
                        if(response.success)
                        {
                          $("<div />").dialog({
                            title: 'Delete Student Enrolment',
                            open: function(){
                              markup = '<h4>Student enrolment record deleted successfully</h4>';
                              $(this).html(markup);
                            },
                            buttons: {
                            Ok: function () {
                                  $(this).dialog("close");
                                }
                            }
                          });
                          $(row_id).remove();
                        }
                        else
                        {
                          $("<div />").dialog({
                            title: 'Delete Failure',
                            open: function(){
                              markup = '<h4>A problem occurred while deleting the student enrolment record</h4>';
                              $(this).html(markup);
                            },
                            buttons: {
                            Ok: function () {
                                  $(this).dialog("close");
                                }
                            }
                          });
                        }
                      }
            });
              $(this).dialog("close");
          },
          Cancel: function(){

            $(this).dialog("close");

          }
        }
    });
  }
  </script>
<table id="" class="table table-hover ">
  <tr>
    <th>First Name</th>
    <th>Surname</th>
    <th>Course</th>
    <th>Year</th>
    <th>Date Signed</th>
    <th>Date Captured</th>
    <th>Edit</th>
    <th>Del</th>
  </tr>

  {% paginate all_students %}
  {% for student in all_students %}

  <tr id=row_{{student.id}}>
    <td>{{ student.student.first_name|default_if_none:"" }}</td> 
    <td>{{ student.student.surname|default_if_none:"" }}</td>
    <td>{{ student.course|default_if_none:"" }}</td>
    <td>{{ student.enrolment_year|default_if_none:"" }}</td>
    <td>{{ student.application_signed|date:'Y-m-d'|default_if_none:"" }}</td>
    <td>{{ student.created_at|default_if_none:"" }}</td>
    <td>
      <a href="{% url 'college:edit_enrolment' student.id %}" data-toggle="" data-toggle="tooltip" data-placement="right" title="Edit Student Enrolment">
        <i class="far fa-check-square"></i></a>
    </td>
    <td>
      <a href="" onclick="delete_policy_comment({{student.id}}, row_{{student.id}});return false;"  data-toggle="" data-toggle="tooltip" data-placement="right" title="Delete Student Enrolment">
        <i class="far fa-trash-alt"></i></a>
    </td>
  </tr>
  {% endfor %}
  <tr>
    <td colspan='13' style="text-align: center">
    <div class="center">
      <div class="pagination">
        {% show_pages %}
      </div>
    </div>
    </td>
  </tr>
</table>

mazintech/templates/college/_students_list.html
{% load el_pagination_tags %}
<script type="text/javascript">
  delete_policy_comment = function(id, row_id){
    $("<div><h4>Are you sure you want to delete this student record?</h4></div>").dialog({
        buttons: {
          Yes: function(){

            $.ajax({
            context: row_id,
            type: 'post',
            url: "{% url 'college:delete_student' %}",
            data: {id: id},
            dataType: 'json',
            success:  function(response){
                        if(response.success)
                        {
                          $("<div />").dialog({
                            title: 'Delete Student',
                            open: function(){
                              markup = '<h4>Student record deleted successfully</h4>';
                              $(this).html(markup);
                            },
                            buttons: {
                            Ok: function () {
                                  $(this).dialog("close");
                                }
                            }
                          });
                          $(row_id).remove();
                        }
                        else
                        {
                          $("<div />").dialog({
                            title: 'Delete Failure',
                            open: function(){
                              markup = '<h4>A problem occurred while deleting the student record</h4>';
                              $(this).html(markup);
                            },
                            buttons: {
                            Ok: function () {
                                  $(this).dialog("close");
                                }
                            }
                          });
                        }
                      }
            });
              $(this).dialog("close");
          },
          Cancel: function(){

            $(this).dialog("close");

          }
        }
    });
  }
  </script>
<table id="" class="table table-hover ">
  <tr>
    <th>First Name</th>
    <th>Surname</th> 
    <th>Gender</th>
    <th>DOB</th>
    <th>ID Number</th>
    <th>Course</th>
    <th>Year</th>
    <th>Region</th>
    <th>District</th>
    <th>Edit</th>
    <th>Enrole</th>
    <th>Del</th>
  </tr>

  {% paginate all_students %}
  {% for student in all_students %}

  <tr id=row_{{student.id}}>    
    <td>{{ student.first_name|default_if_none:"" }}</td> 
    <td>{{ student.surname|default_if_none:"" }}</td>
    <td>{{ student.get_gender_display }}</td>
    <td>{{ student.date_of_birth|date:'Y-m-d'|default_if_none:"" }}
    <td>{% if student.id_number %}
          {{ student.id_number|default_if_none:"" }}
        {% else %}
          {{ student.passport|default_if_none:"" }}
        {% endif %}
    </td>
    <td>{{ student.course|default_if_none:"" }}</td>
    <td>{{ student.course_year|default_if_none:"" }}</td>
    <td>{{ student.region|default_if_none:"" }}</td>
    <td>{{ student.district|default_if_none:"" }}</td>
    <td>
      <a href="{% url 'college:edit_student' student.id %}" data-toggle="" data-toggle="tooltip" data-placement="right" title="Edit Student">
        <i class="far fa-edit"></i></i></a>
    </td>
    <td>
      <a href="{% url 'college:add_enrolment' student.id %}" data-toggle="" data-toggle="tooltip" data-placement="right" title="Edit Student Enrolment">
        <i class="far fa-check-square"></i></a>
      </td>
    <td>
      <a href="" onclick="delete_policy_comment({{student.id}}, row_{{student.id}});return false;" data-toggle="" data-toggle="tooltip" data-placement="right" title="Edit Student">
      <i class="far fa-trash-alt"></i></a>
    </td>
  </tr>
  {% endfor %}
  <tr>
    <td colspan='13' style="text-align: center">
    <div class="center">
      <div class="pagination">
        {% show_pages %}
      </div>
    </div>
    </td>
  </tr>
</table>

mazintech/templates/college/courses.html
{% extends "base.html" %}
{% load staticfiles%}
{% load bootstrap4 %}
{% load humanize %}
{% block javascript %}
  <script src="{% static 'js/custom.js' %}"></script>
{% endblock %}

{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Courses List</b>
    
  </div> 
  <div class="panel-body">

    <form id="course_filter_form" method="GET">
    <div class="row">
        <input name="filter" type="hidden">
        
        <div class='col-lg-3 pull-right'>
          <div class='pull-right'>
            <button type="submit" name="search" class="btn btn-primary" title="Search"><i class="fa fa-search"></i> Search</button>
            
            <a href="{% url 'college:courses' %}"  class="btn btn-primary" title="Clear Search"><i class="fa fa-search-minus"></i> Clear</a>
            
            <button type="submit" id="load_modal" class="btn btn-primary" title="Extract Courses"><i class="fa fa-download"></i> Extract</button>
            <a href="{% url 'college:add_course' %}" class="btn btn-primary" title="Add Course"><i class="fa fa-plus"></i> Add New</a> 
          </div>
        </div>
        
      <div class='col-lg-9'>
        <div class='col-lg-3'>
          {% bootstrap_field course_filter_form.course layout='inline' %}
        </div>
        <div class='col-lg-3'>
        </div>

        <div class='col-lg-3'>
        </div>
    
      </div> 
    </div>
    
    <div class="tab-content">
      <div id="course" class="tab-pane fade in active">
        {% include 'college/_courses_list.html' %}

      </div>
    </div>

    <div class="modal fade" id="extract_modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="modalLabel"><i class="fa fa-info-circle" aria-hidden="true"></i> Extract Course(s)</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <b> Are you sure you want to download the extract</b>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <button type="submit" name="extract" id="extract" class="btn btn-primary">Ok</button>
            </div>
          </div>
        </div>     
    </div>
  </form>
  </div>
</div>
{% endblock %}

mazintech/templates/college/edit_course.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% load humanize %}
{% block javascript %}
  <script src="{% static 'js/students.js' %}"></script>
{% endblock %}

{% block content%}

<div class="panel panel-primary transparency">
  <div class="panel-heading">
    {% if course %}
    <b>Edit Course:</b>
    {% else %}
    <b>Add Course:</b>
    {% endif %}
  </div>
  
  <div class="panel-body">
    
    <form method="POST" class="form-2" novalidate enctype="multipart/form-data">
      {% csrf_token %}
      
      <div id="edit_student_tab_content" class="tab-content">
        <div class="tab-pane fade active in" id="details">
          <br>
          <div class='col-md-6'>
            {% bootstrap_field course_form.course_name %}
          </div>
          
          </div>
      </div>

      <div class="btn-group-horizontal col-lg-12">
        <div class='pull-right'>
          <button type="submit" class="btn btn-primary">
            <i class='fa fa-floppy-o'></i> Save
          </button>
          <a href="{% url 'college:courses' %}" class="btn btn-primary">
            <i class='fa fa-undo'></i> Cancel
          </a>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}

mazintech/templates/college/student_uploads.html
{% extends "base.html" %}
{% load staticfiles %}
{% load bootstrap4 %}
{% load humanize %}

{% block content%}
<div class="panel panel-primary transparency">
  <div class="panel-heading">
    <b>Upload Fuel Card Usage</b>
  </div>

  <div class="panel-body">
    <form method='post' enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <br>
      <button class="btn btn-primary pull-right">Updating Fuel Card Usage</button>
    </form>
  </div>
</div>
{% endblock %}