mazintech/college/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.contrib import admin
from dal import autocomplete

import views
from college.graphs import *
# from mazintech.autocomplete import *

from .models import *
from mazintech.models import *

urlpatterns = [
    url(r'^student/edit/(?P<student_id>\d+)/$', views.edit_student, name='edit_student'),
    url(r'^student/add/$', views.edit_student, name='add_student'), 
    url(r'^students/$', views.students, name='students'),
    url(r'^enrolments/$', views.enrolments, name='enrolments'),
    url(r'^courses/$', views.courses, name='courses'),
    url(r'^student-enrolment/edit/(?P<enrolment_id>\d+)/$', views.edit_enrolment, name='edit_enrolment'),
    url(r'^student-enrolment/add/(?P<student_id>\d+)/$', views.edit_enrolment, name='add_enrolment'),
    url(r'^student-enrolment/$', views.edit_enrolment, name='add_new_enrolment'),
    url(r'^course/edit/(?P<course_id>\d+)/$', views.edit_course, name='edit_course'),
    url(r'^course/add/$', views.edit_course, name='add_course'),
    url(r'^course-delete/$', views.delete_course, name='delete_course'),
    url(r'^student-delete/$', views.delete_student, name='delete_student'),
    url(r'^enrolment-delete/$', views.delete_enrolment, name='delete_enrolment'),
    url(r'^course-totals/$', courseTotalEnrolmentData.as_view(), name='course_totals'),
    url(r'^current-totals/$', currentTotalEnrolmentData.as_view(), name='current_totals'),
    url(r'^regional-totals/$', regionalTotalEnrolmentData.as_view(), name='regional_totals'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mazintech/mazintech/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from django_js_reverse.views import urls_js
from models import RegionAutoComplete,DistrictAutoComplete

urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^region_autocomplete/$', RegionAutoComplete.as_view(), name='region_autocomplete'),
    url(r'^district_autocomplete/$', DistrictAutoComplete.as_view(), name='district_autocomplete'),

    url(r'^jsreverse/$', urls_js, name='js_reverse'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout,{'next_page':'/'}, name='logout'),

    url(r'^about/$', views.about, name='about'),
    url(r'^users$', views.users, name='users'),
    url(r'^users/college-admins/(?P<college_administrators>\d+)/$', views.users, name='college_admins'),
    url(r'^user/add/$', views.user_edit, name='user_add'),
    url(r'^user/edit/(?P<user_id>\d+)/$', views.user_edit, name='user_edit'),

    url(r'^', include('college.urls', namespace='college')),

    url(r'^regions$', views.view_regions, name='view_regions'),
    url(r'^branches$', views.view_branches, name='view_branches'),

    url(r'^downloads/$', views.downloads_list, name="view_downloads"),
    url(r'^downloads/(?P<file_id>\d+)/$', views.file_download_task, name="file_download"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mazintech/templates/_css.html
{% load staticfiles %}


<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">  

<link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet">     

<link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">

<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">

<link href="{% static 'css/all.css' %}" rel="stylesheet">

<link href="{% static 'css/bootstrap-submenu.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet"> 

<link href="{% static 'css/custom.css' %}" rel="stylesheet">
<!-- <link href="{% static 'css/nprogress.css' %}" rel="stylesheet"> -->
<!-- <link href="{% static 'css/custom.min.css' %}" rel="stylesheet"> -->
<link href="{% static 'css/base.css' %}" rel="stylesheet"> 

<link href="{% static 'css/metisMenu.min.css' %}" rel="stylesheet"> 

<link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

<link href="{% static 'css/morris.css' %}" rel="stylesheet"> 

<link href="{% static 'css/vehicle_panel.css' %}" rel="stylesheet">
<link href="{% static 'css/vehicle.css' %}" rel="stylesheet">

<link rel="stylesheet" type="text/css" href="{% static 'autocomplete_light/vendor/select2/dist/css/select2.css' %}" />

<link href="{% static 'css/panel.css' %}" rel="stylesheet">

<link href="{% static 'css/bootstrap-multiselect.css' %}" rel="stylesheet">

mazintech/templates/_scripts.html
{% load staticfiles %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

<script type="text/javascript" src="{% static 'autocomplete_light/jquery.init.js' %}"></script>
<script type="text/javascript" src="{% static 'autocomplete_light/autocomplete.init.js' %}"></script>    
<script type="text/javascript" src="{% static 'autocomplete_light/select2.js' %}"></script>

<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'js/bootstrap-multiselect.min.js' %}"></script>


<!-- <script src="{% static 'js/fastclick.js' %}"></script>
<script src="{% static 'js/nprogress.js' %}"></script>
<script src="{% static 'js/Chart.min.js' %}"></script>
<script src="{% static 'js/custom.min.js' %}"></script> -->


<script src="{% static 'js/select2.min.js' %}"></script>
<script src="{% static 'js/bootstrap-submenu.min.js' %}"></script>
<script src="{% static 'js/dj-reverse.js' %}"></script>

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

<script>
$(function() {
  $('a[data-toggle="pill"]').on('shown.bs.tab', function (e) {
    localStorage.setItem('lastTab', $(this).attr('href'));
  });
  var lastTab = localStorage.getItem('lastTab');
  if (lastTab) {
    $('[href="' + lastTab + '"]').tab('show');
  }
});
</script>

<script src="{% static 'js/vehicle_panel.js' %}"></script>

mazintech/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <link rel="icon" href="../../favicon.ico"> -->
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
    <title>Mazintech</title>
    {% include '_css.html' %}

    {% block extra_css %}
    {% endblock %}

    <style>
    
    {% block style %}
    

    {% endblock %}
    
    </style>
    {% include '_scripts.html' %}

    {% block javascript %}
    {% endblock %}
  </head>

  <body>
    <div class="bg_fixed"></div>
    <div class="outer_wrapper">
      
      {% block body %}
      
      <div class="content_wrapper">

        {% include 'navbar.html' %}
        <div style="clear:both"></div>
        
        {% block extra_content %}
        {% endblock %}
        
        <div class="content">
          <br/>
          {% if messages %}
          
          {% for message in messages %}
          <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}info{% endif %}">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            <strong>{{ message }}</strong>
          </div>
          {% endfor %}
          
          {% endif %}

          {% block content %}
          {% endblock %}
          
        </div>
        
      </div>
      
      {% endblock %}
      
      <div class="push_footer"> </div>
      <div style="clear:both"></div>
      
    </div>
  </body>
</html>

mazintech/templates/loading.html
{% load staticfiles%}
<div class="load_spinner">	
 <img id="id_loading" src="{% static 'img/busy.gif' %}"/>	
</div>

mazintech/templates/login_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Mazintech</title>
    {% include '_css.html' %}
    <style>
    {% block style %}{% endblock %}
    </style>
    {% include '_scripts.html' %}

    {% block javascript %}
    {% endblock %}
  </head> 

  <body class="bodybaground" style="background-image: url({% static 'img/gold_bg1.jpg' %}); background-repeat: no-repeat; background-size: 100%, 100%;" >  

    <div class="container"> 
      
      {% block content %}
      {% endblock %}
      
    </div>
  </body>
</html>

mazintech/templates/navbar.html
{% load staticfiles%}

<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class=" row col-sm-12 col-sm-offset-0">
    <div class="navbar-header">
        <a href="{% url 'home' %}">
            <img src="{% static 'img/logo.png' %}" style="height:50px; cursor:pointer">
        </a>
    </div>
    <div class=" collapse navbar-collapse navbar-font" id="navbar">
        <ul class="nav navbar-nav">
          {% if not request.user.is_mazintech_employee %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle panel_field" href="#" id="FleetNavbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
                    College <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu" aria-labelledby="FleetNavbarDropdown">
                    <li>
                        <a class="dropdown-item" href="{% url 'college:students' %}"><i class="fa fa-list-ol" aria-hidden="true"></i>&nbsp;&nbsp;Students</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'college:courses' %}"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i>&nbsp;&nbsp;Courses</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'college:enrolments' %}"><i class="fas fa-file-invoice" aria-hidden="true"></i>&nbsp;&nbsp;Enrolment</a>
                    </li>
                </ul>
            </li>

                <li class="nav-item"><a class="nav-link" href="{% url 'view_downloads' %}">Downloads</a></li>
            {% endif %}

            {% if request.user.is_superuser %}
                <li class="nav-item"><a class="nav-link" href="{% url 'users' %}">Users</a></li>
            {% endif %}

          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item"><a class="nav-link" href="#">Welcome {{ request.user }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          </ul>
    </div>
  </div>
</nav>